os: linux
dist: trusty

matrix:
  include:
    - language: php

      php:
      - 7.2

      addons:
        chrome: stable

      services: mysql

      before_install:
        - mysql -e 'CREATE DATABASE fronds_test;'

      install:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        - chmod +x php-coveralls.phar
        - cp .env.testing .env
        - travis_retry composer install --no-interaction --prefer-dist --no-suggest
        - php artisan key:generate
        - php artisan dusk:update 76
        - php artisan migrate

      before_script:
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - php artisan serve &

      script:
        - php artisan dusk
        - phpunit
      after_success:
        - travis_retry php php-coveralls.phar

    - language: node_js

      node_js:
        - 10.15

      install:
        - npm install
        - travis_retry npm install --global eslint @vue/cli

      script:
        - npm run lint

